apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a4s3t7jwb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a4s3t7jwb-go 
  name: a4s3t7jwb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: a4s3t7jwb-go 
